document.writeln("  <footer class=\'footer-section-2 bg--dark-8 position-relative overflow-hidden\'>");
document.writeln("    <div class=\'circle-1\'></div>");
document.writeln("    <div class=\'circle-2\'></div>");
document.writeln("    <div class=\'container\'>");
document.writeln("      <div class=\'pt-120 pb-120\'>");
document.writeln("        <div class=\'row gy-5\'>");
document.writeln("          <div class=\'col-lg-3 col-sm-6\'>");
document.writeln("            <div class=\'text-start footer-about\'>");
document.writeln("              <div class=\'footer-logo mb-25 ms-0\'>");
document.writeln("                <a href=\'#0\'>");
document.writeln("                  <img src=\'assets/images/logo.png\' alt=\'footer\'>");
document.writeln("                </a>");
document.writeln("              </div>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-lg-3 col-sm-6\'>");
document.writeln("            <div class=\'text-start footer-widget social-border-color-1\'>");
document.writeln("              <h6 class=\'footer__title text-white\'>Wallets</h6>");
document.writeln("              <ul class=\'footer__links\'>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#0\'>Windows</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#0\'>Web</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#0\'>Android</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#0\'>IOS</a>");
document.writeln("                </li>");
document.writeln("              </ul>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-lg-3 col-sm-6\'>");
document.writeln("            <div class=\'text-start footer-widget social-border-color-1\'>");
document.writeln("              <h6 class=\'footer__title text-white\'>BTCS Resources </h6>");
document.writeln("              <ul class=\'footer__links\'>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#0\'>Bitcoin Silver Core</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#0\'>Blockchain</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#0\'>Explorer</a>");
document.writeln("                </li>");
document.writeln("                <li>");
document.writeln("                  <a href=\'#0\'>Official Mining Pool</a>");
document.writeln("                </li>");
document.writeln("              </ul>");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("    </div>");
document.writeln("    <div class=\'footer-bottom text-white\'>");
document.writeln("      <div class=\'container\'>");
document.writeln("        <div class=\'row g-2\'>");
document.writeln("          <div class=\'col-lg-6\'>");
document.writeln("            <div class=\'copyright text-center text-lg-start\'>");
document.writeln("              Copyright &copy; 2024 <a href=\'#\' class=\'text-white fw--semibold text-decoration-none\'>BTCS </a> all");
document.writeln("              right.");
document.writeln("            </div>");
document.writeln("          </div>");
document.writeln("          <div class=\'col-lg-6\'>");
document.writeln("            <ul class=\'quick-links justify-content-center justify-content-lg-end\'>");
document.writeln("              <li>");
document.writeln("                <a href=\'#0\'>Term of Use</a>");
document.writeln("              </li>");
document.writeln("              <li>");
document.writeln("                <a href=\'#0\'>Privacy Policy</a>");
document.writeln("              </li>");
document.writeln("            </ul>");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </footer>");