document.writeln(" <!-- Header Section -->");
document.writeln("  <header class=\'header-section\'>");
document.writeln("    <div class=\'container\'>");
document.writeln("      <div class=\'header-area\'>");
document.writeln("        <div class=\'logo me-auto\'>");
document.writeln("                  <img src=\'assets/images/logo.png\' alt=\'footer\'>");
document.writeln("        </div>");
document.writeln("        <ul class=\'menu\'>");
document.writeln("          <li>");
document.writeln("            <a href=\'#\'>home</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("            <a href=\'#token\'>Ecosystem</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("            <a href=\'#road\'>ROADMAP</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("            <a href=\'#team\'>TEAM</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("            <a href=\'#faq\'>WALLET</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("            <a href=\'#how\'>MINNG</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("            <a href=\'contact.html\'>COMMUNITY</a>");
document.writeln("          </li>");
document.writeln("          <li>");
document.writeln("            <div class=\'header-buttons d-flex flex-wrap justify-content-center d-md-none\'>");
document.writeln("              <a href=\'#0\' class=\'cmn--btn m-3\'>Login</a>");
document.writeln("            </div>");
document.writeln("          </li>");
document.writeln("        </ul>");
document.writeln("        <ul class=\'menu\'>");
document.writeln("          <li class=\'en\'><a href=\'#\' class=\'aaa\' style=\'color: #fff; text-decoration: none\'>En</a></li>");
document.writeln("          <ul class=\'submenu\' style=\'background: #fff;\'>");
document.writeln("            <li><a style=\'color: #6d6d6d; text-decoration: none\' href=\'#\'>En</a></li>");
document.writeln("            <li><a style=\'color: #6d6d6d;text-decoration: none\' href=\'#\'>Bn</a></li>");
document.writeln("            <li><a style=\'color: #6d6d6d;text-decoration: none\' href=\'#\'>Pk</a></li>");
document.writeln("            <li><a style=\'color: #6d6d6d;text-decoration: none\' href=\'#\'>In</a></li>");
document.writeln("            <li><a style=\'color: #6d6d6d;text-decoration: none\' href=\'#\'>Us</a></li>");
document.writeln("          </ul>");
document.writeln("        </ul>");
document.writeln("");
document.writeln("        <div class=\'header-buttons d-none d-md-flex\'>");
document.writeln("          <a href=\'#0\' class=\'cmn--btn btn-pill btn--8\'>SET STARTED</a>");
document.writeln("        </div>");
document.writeln("        <div class=\'header-bar d-lg-none ms-3\'>");
document.writeln("          <span></span>");
document.writeln("          <span></span>");
document.writeln("          <span></span>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </div>");
document.writeln("  </header>");
document.writeln("  <!-- Header Section -->");